### ISSUE TITLE
Want to add Hover Properties over the cards

### ISSUE THREAD

**Issue by IIITManjeet** [sparshmahajan/movie-db#2]
Kindly assign me this issue.

**Comment by sparshmahajan** [comment]
I have assigned this work to you. Please make sure about the phone view too.

**Comment by IIITManjeet** [comment]
ok

**Comment by IIITManjeet** [comment]
Sir there is one problem while running the project in localhost that it is showing CORS error

**Comment by sparshmahajan** [comment]
U need to run backend on localhost too and need to change link to localhost too
